name: ROS C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Clean ROS project
      run: |
        cd ros 
        catkin_make clean
    - name: Build ROS project
      run: |
        cd ros
        catkin_make
