name: ROS C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Install ROS 
      run: | 
        sudo bash -c 'ls /'
#    - name: Clean ROS Vision package
#      run: |
#        cd ros/src/vision
#        rm -rf ./build
#    - name: Build ROS Vision package
#      run: |
#        cd ros/src/vision
#        mkdir build
#        cd build
#        cmake ..


#        sudo bash -c 'touch etc/apt/sources.list'
#        sudo bash -c 'echo "deb http://packages.ros.org/ros/ubuntu xenial main" > etc/apt/sources.list'
#        sudo bash -c 'apt-key adv --keyserver "hkp://keyserver.ubuntu.com:80" --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654'
