name: ROS C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Clean ROS Vision package
      run: |
        cd ros/src/vision
        rm -rf ./build
    - name: Build ROS Vision package
      run: |
        cd ros/src/vision
        mkdir build
        cd build
        cake ..
